# Generated by Django 4.2 on 2023-04-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
